ProjetoLP/AngelinaPrj/Controllers/MateriaController.cs
using AngelinaPrj.Models;
using AngelinaPrj.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AngelinaPrj.Controllers
{
    [Authorize(Roles = "Professor")]
    public class MateriaController : Controller
    {
        private PrjContext db = new PrjContext();

        // GET: Materia/
        public ActionResult Index(int ? CursoId)
        {
            if (CursoId == null)
            {
                return View(db.Materias.ToList());
            }

            return View(db.Materias.Where(m => m.CursoId == CursoId).ToList());
        }

        //GET: Materia/CadastrarMateria
        public ActionResult CadastrarMateria(int CursoId, int EscolaId)
        {
            CadastroMateriaViewModel materia = new CadastroMateriaViewModel
            {
                CursoId = CursoId
            };

            return View(materia);
        }

        //POST: Materia/CadastrarMateria
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CadastrarMateria(CadastroMateriaViewModel viewmodel, int CursoId, int EscolaId)
        {
            if (!ModelState.IsValid)
            {
                return View(viewmodel);
            }

            if (db.Materias.Count(m => m.Nome == viewmodel.Nome) > 0)
            {
                if (db.Materias.Count(m => m.CursoId == CursoId) > 0)
                {
                    ModelState.AddModelError("Nome", "Esta matéria já está cadastrada neste curso !");
                    return View(viewmodel);
                }
            }

            Materia materia = new Materia
            {
                Nome = viewmodel.Nome,
                Descricao = viewmodel.Descricao,
                Professor = viewmodel.Professor,
                CursoId = CursoId
            };

            db.Materias.Add(materia);
            db.SaveChanges();

            var queryUltimaMateria =
                (from m in db.Materias
                 orderby m.MateriaId descending
                 select new { m.MateriaId }).First();

            Curso_Materia curso_Materia = new Curso_Materia
            {
                CursoId = materia.CursoId,
                MateriaId = queryUltimaMateria.MateriaId
            };

            db.Cursos_Materias.Add(curso_Materia);
            db.SaveChanges();

            return RedirectToAction("DetalhesCurso", "Curso", new { CursoId = CursoId, EscolaId = EscolaId});
        }

        //GET: Materia/EditarMateria
        public ActionResult EditarMateria(int ? MateriaId)
        {
            if (MateriaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Materia materia = db.Materias.Find(MateriaId);

            if (materia == null)
            {
                return HttpNotFound();
            }

            return View(materia);
        }

        //POST: Materia/EditarMateria
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarMateria([Bind(Include = "MateriaId, Nome, Descricao")]Materia materia)
        {
            if (!ModelState.IsValid)
            {
                return View(materia);
            }

            db.Entry(materia).State = EntityState.Modified;
            db.SaveChanges();

            return View(materia);
        }

        //GET: Materia/DeletarMateria
        public ActionResult Delete(int ? MateriaId, int ? CursoId)
        {
            if (MateriaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Materia materia = db.Materias.Find(MateriaId);

            if (materia == null)
            {
                return HttpNotFound();
            }

            return View(materia);
        }

        //POST: Materia/DeletarMateria
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int MateriaId)
        {
            Materia materia = db.Materias.Find(MateriaId);
            db.Materias.Remove(materia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //GET: Materia/DetalhesMateria
        public ActionResult DetalhesMateria(int ? MateriaId)
        {
            if (MateriaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Materia materia = db.Materias.Find(MateriaId);

            if (materia == null)
            {
                return HttpNotFound();
            }

            var salas = db.Materias_Salas.Where(m => m.MateriaId == materia.MateriaId).ToList();

            if (salas == null)
            {
                return HttpNotFound();
            }

            var viewmodel = new DetalhesMateriaViewModel
            {
                Materia = materia,
                
                Materia_Salas = salas
            };
            

            return View(viewmodel);
        }
    }
}

ProjetoLP/AngelinaPrj/Controllers/MateriaisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AngelinaPrj.Models;
using AngelinaPrj.ViewModel;

namespace AngelinaPrj.Controllers
{
    public class MateriaisController : Controller
    {
        private PrjContext db = new PrjContext();

        // GET: Materiais/DetalhesMaterial/
        [Authorize]
        public ActionResult DetalhesMaterial(int ? MaterialId)
        {
            if (MaterialId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Material material = db.Materiais.Find(MaterialId);

            if (material == null)
            {
                return HttpNotFound();
            }

            var exercicios = db.Exercicios.Where(m => m.MaterialId == MaterialId).ToList();

            var view = new DetalhesMaterialViewModel()
            {
                Material = material,
                Exercicios = exercicios
            };

            return View(view);
        }

        // GET: Materiais/CadastrarMaterial/
        [Authorize(Roles = "Professor")]
        public ActionResult CadastrarMaterial(int ? SalaId)
        {
            if (SalaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            else {
                int salaId = Convert.ToInt16(SalaId);

                CadastroMaterialViewModel material = new CadastroMaterialViewModel
                {
                    SalaId = salaId
                };

                return View(material);
            }
        }

        // POST: Materiais/CadastrarMaterial/
        [Authorize(Roles = "Professor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CadastrarMaterial(HttpPostedFileBase file, CadastroMaterialViewModel viewmodel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewmodel);
            }

            if (db.Materiais.Count(m => m.Assunto == viewmodel.Assunto) > 0)
            {
                if (db.Materiais.Count(m => m.Sala.SalaId == viewmodel.SalaId) > 0)
                {
                    ModelState.AddModelError("Assunto", "Este material já existe, altere o assunto para não gerar ambiguidade.");
                    return View(viewmodel);
                }
            }

            if (file.ContentLength > 0)
            {
                var nomeArquivo = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Uploads"), nomeArquivo);

                file.SaveAs(path);

                Material material = new Material
                {
                    Resumo = viewmodel.Resumo,
                    Assunto = viewmodel.Assunto,
                    Data = DateTime.Now,
                    Descricao = viewmodel.Descricao,
                    SalaId = viewmodel.SalaId,
                    Arquivo = path
                };

                db.Materiais.Add(material);
            }
            else
            {
                Material material = new Material
                {
                    Resumo = viewmodel.Resumo,
                    Assunto = viewmodel.Assunto,
                    Data = DateTime.Now,
                    Descricao = viewmodel.Descricao,
                    SalaId = viewmodel.SalaId
                };

                db.Materiais.Add(material);
            }

            db.SaveChanges();

            var queryUltimoMaterial =
                (from m in db.Materiais
                 orderby m.MaterialId descending
                 select new { m.MaterialId }).First();


            return RedirectToAction("DetalhesMaterial", new { MaterialId = queryUltimoMaterial.MaterialId});
        }

        //GET: Materiais/DownloadMaterial/
        [Authorize]
        public FileResult DownloadMaterial(string arquivo)
        {
            var path = arquivo;

            FileStream fileStream;

            fileStream = System.IO.File.OpenRead(path);

            string contentType = "application/pdf";

            return File(fileStream, contentType);
        }

        // GET: Materiais/EditarMaterial/
        public ActionResult EditarMaterial(int? MaterialId)
        {
            if (MaterialId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Material material = db.Materiais.Find(MaterialId);

            if (material == null)
            {
                return HttpNotFound();
            }

            return View(material);
        }

        [Authorize(Roles = "Professor")]
        // POST: Materiais/EditarMaterial/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarMaterial([Bind(Include = "MaterialId,Assunto,Data,Descricao,Arquivo")] Material material)
        {
            if (ModelState.IsValid)
            {
                db.Entry(material).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(material);
        }

        // GET: Materiais/Delete/
        [Authorize(Roles = "Professor")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Material material = db.Materiais.Find(id);
            if (material == null)
            {
                return HttpNotFound();
            }
            return View(material);
        }

        // POST: Materiais/Delete/
        [Authorize(Roles = "Professor")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Material material = db.Materiais.Find(id);
            db.Materiais.Remove(material);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetoLP/AngelinaPrj/Controllers/SalaController.cs
using AngelinaPrj.Models;
using AngelinaPrj.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace AngelinaPrj.Controllers
{
    [Authorize]
    public class SalaController : Controller
    {
        private PrjContext db = new PrjContext();

        // GET: Sala/
        [Authorize(Roles = "Professor")]
        public ActionResult Index(int ? MateriaId)
        {
            if (MateriaId == null)
            {
                return View(db.Salas.ToList());
            }
            var listaSalas = new List<Materia_Sala>();
            listaSalas = db.Materias_Salas.Where(s => s.MateriaId == MateriaId).ToList();

            var listaMaterias = new List<Materia>();
            listaMaterias = db.Materias.ToList();

            ViewBag.Materias = listaMaterias;

            return View(listaSalas);
        }

        //GET: Sala/CadastrarSala
        [Authorize(Roles = "Professor")]
        public ActionResult CadastrarSala(int MateriaId)
        {
            CadastroSalaViewModel sala = new CadastroSalaViewModel
            {
                MateriaId = MateriaId
            };

            return View(sala);
        }

        //POST: Sala/CadastrarSala
        [Authorize(Roles = "Professor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CadastrarSala(CadastroSalaViewModel viewmodel, int MateriaId)
        {
            if (!ModelState.IsValid)
            {
                return View(viewmodel);
            }
                Random rand = new Random((int)DateTime.Now.Ticks);
                var CodigoSala = 0;
                CodigoSala = rand.Next(1000, 9999);

            //criar aqui as querys que procuram o nome da escola e da matéria
            //pela matéria eu consigo o curso e pelo curso eu consigo a escola

            var queryNomeMateria =
                (from nMateria in db.Materias
                 where nMateria.MateriaId == MateriaId
                 select new { nMateria.Nome }).Single();

            var queryCursoId =
                (from cId in db.Materias
                 where cId.MateriaId == MateriaId
                 select new { cId.CursoId }).Single();

            var queryEscolaId =
                (from eId in db.Cursos
                 where eId.CursoId == queryCursoId.CursoId
                 select new { eId.EscolaId }).Single();

            var queryNomeEscola =
                (from nEscola in db.Escolas
                 where nEscola.EscolaId == queryEscolaId.EscolaId
                 select new { nEscola.Nome }).Single();

            Sala sala = new Sala
            {
                Semestre = viewmodel.Semestre,
                Situacao = viewmodel.Situacao,
                Periodo = viewmodel.Periodo,
                CodigoSala = CodigoSala,
                Escola = queryNomeEscola.Nome,
                Materia = queryNomeMateria.Nome
            };

            db.Salas.Add(sala);
            db.SaveChanges();

            Materia_Sala sala_materia = new Materia_Sala
            {
                MateriaId = MateriaId,
                SalaId = sala.SalaId
            };

            db.Materias_Salas.Add(sala_materia);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        //GET Sala/SalasAluno
        [Authorize(Roles = "Aluno")]
        public ActionResult SalasAlunoById(int UsuarioId)
        {
            var queryVerificaAluno = db.Usuarios.Where(u => u.Nome == User.Identity.Name).FirstOrDefault();

            int IdUsuarioSolicitado = queryVerificaAluno.UsuarioId;

            if (UsuarioId == IdUsuarioSolicitado)
            {
                var querySalasDoAluno = db.Alunos_Sala.AsQueryable().AsEnumerable();

                querySalasDoAluno = querySalasDoAluno.Where(s => s.UsuarioId == UsuarioId);

                return View(querySalasDoAluno);
            }

            else
            {
                return RedirectToAction("Index", "Home", null);
            }
        }

        //GET Sala/SalasAluno
        [Authorize]
        public ActionResult SalasAlunoByName(string NomeUsuario)
        {
            var queryProcuraIdUsuario = db.Usuarios.AsQueryable().Where(u => u.Nome == NomeUsuario).FirstOrDefault();

            int UsuarioId = queryProcuraIdUsuario.UsuarioId;

            return (RedirectToAction("SalasAlunoById", new { UsuarioId = UsuarioId}));
        }

        //GET: Sala/EditarSala
        [Authorize(Roles = "Professor")]
        public ActionResult EditarSala(int ? SalaId)
        {
            if (SalaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Sala sala = db.Salas.Find(SalaId);

            if (sala == null)
            {
                return HttpNotFound();
            }

            return View(sala);
        }


        //POST: Sala/EditarSala
        [Authorize(Roles = "Professor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarSala([Bind(Include = "SalaId, Semestre, Situacao, Periodo, CodigoSala, Escola, Materia")] Sala sala)
        {
            if (!ModelState.IsValid)
            {
                return View(sala);
            }

            db.Entry(sala).State = EntityState.Modified;
            db.SaveChanges();

            return View(sala);
        }

        //GET Sala/DetalhesSala
        [Authorize(Roles = "Aluno, Professor")]
        public ActionResult DetalhesSala(int? SalaId)
        {
            if (SalaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Sala sala = db.Salas.Find(SalaId);

            if (sala == null)
            {
                return HttpNotFound();
            }

            var materiais = db.Materiais.Where(m => m.Sala.SalaId == sala.SalaId).ToList();

            if (materiais == null)
            {
                return HttpNotFound();
            }

            var viewmodel = new DetalhesSalaViewModel
            {
                Sala = sala,

                Materiais = materiais
            };

            return View(viewmodel);
        }
    }
        
}

ProjetoLP/AngelinaPrj/Views/Sala/CadastrarSala.cshtml
@model AngelinaPrj.ViewModel.CadastroSalaViewModel

@{
    ViewBag.Title = "CadastrarSala";
}

<h2>CadastrarSala</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CadastroSalaViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Semestre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Semestre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Semestre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Situacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Situacao)
                    @Html.ValidationMessageFor(model => model.Situacao, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Periodo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Periodo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Periodo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProjetoLP/AngelinaPrj/Views/Sala/DetalhesSala.cshtml
@model AngelinaPrj.ViewModel.DetalhesSalaViewModel

@{
    ViewBag.Title = "DetalhesSala";
}
<div class="container">
    <div class="row col-8 d-block mx-auto m-3">
        <h2 class="pt=2 text-center">Materiais e Exercícios da sala de @Model.Sala.Materia em @Model.Sala.Escola</h2>
    </div>
        @foreach (var material in Model.Materiais)
        {
            <div class="col-10 card text-center mb-4 d-block mx-auto">
                <div class="card-header">
                    @material.Assunto
                </div>
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">@material.Descricao</p>
                    @Html.ActionLink("Ver material e seu exercícios", "DetalhesMaterial", "Materiais", new { MaterialId = material.MaterialId }, new { @class = "btn btn-primary" })
                </div>
                <div class="card-footer text-muted">
                    @material.Data
                </div>
            </div>
        }
    <p>
        @Html.ActionLink("Adicionar Material", "CadastrarMaterial", "Materiais", new { SalaId = Model.Sala.SalaId }, new { @class = "btn btn-success" }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

ProjetoLP/AngelinaPrj/Views/Sala/EditarSala.cshtml
@model AngelinaPrj.Models.Sala

@{
    ViewBag.Title = "EditarSala";
}

<h2>EditarSala</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sala</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SalaId)

        <div class="form-group">
            @Html.LabelFor(model => model.Semestre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Semestre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Semestre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Periodo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Periodo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Periodo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodigoSala, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodigoSala, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodigoSala, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Escola, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Escola, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Escola, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Materia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Materia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Materia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="custom-control custom-switch">
            @Html.EditorFor(model => model.Situacao, new { htmlAttributes = new { @type = "checkbox", @class = "custom-control-input", @id = "Situacao" } })
            @Html.LabelFor(model => model.Situacao, htmlAttributes: new { @class = "custom-control-label col-md-2", @for = "Situacao" })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProjetoLP/AngelinaPrj/Views/Sala/Index.cshtml
@model IEnumerable<AngelinaPrj.Models.Sala>

@{
    ViewBag.Title = "Index";
}

<div class="container">
    <h2 class="text-center m-2">Todas as salas</h2>
    <div class="col-12">
        <div class="row justify-content-center">
            @foreach (var sala in Model)
            {
            <div class="card text-white bg-dark m-3 text-center" style="max-width: 18rem;">
                <div class="card-header">Escola: @sala.Escola</div>
                <div class="card-body">
                    <p class="card-text">Semestre: @sala.Semestre</p>
                    <p class="card-text">Período: @sala.Periodo</p>
                    <p class="card-text">Materia: @sala.Materia</p>
                    @{
                        if (sala.Situacao == true)
                        {
                            <p class="card-text"><span class="badge badge-success">Em andamento</span></p>
                        }
                        else
                        {
                            <span class="badge badge-danger">Sala fechada !</span>
                        }
                    }
                </div>
                @Html.ActionLink("Ver materiais da sala", "DetalhesMateria", "Materia", null , new { @class = "btn btn-primary mx-1 my-1" })
                @Html.ActionLink("Alterar situação", "EditarSala", "Sala", new { SalaId = sala.SalaId}, new { @class = "btn btn-danger mx-1 my-1" })
            </div>
            }
        </div>
        @Html.ActionLink("Nova Sala", "CadastrarSala", "Sala", new {  }, null)
    </div>
</div>

ProjetoLP/AngelinaPrj/Views/Sala/SalasAlunoById.cshtml
@model IEnumerable<AngelinaPrj.Models.Aluno_Sala>

@{
    ViewBag.Title = "SalasAlunoById";
}
<div class="container height-80">
    <h2 class="text-center mt-2">Suas salas:</h2>
    <div class="col-12">
        <div class="row justify-content-center">
            @foreach (var sala in Model)
            {

                <div class="card text-white bg-dark m-3 text-center" style="max-width: 18rem;">
                    <div class="card-header">Semestre: @sala.Sala.Semestre</div>
                    <div class="card-body">
                        <p class="card-text">@sala.Sala.Periodo</p>
                    </div>
                    @Html.ActionLink("Ver materiais e exercícios", "DetalhesSala", "Sala", new { SalaId = sala.SalaId }, new { @class = "btn btn-primary mx-1 my-1" })
                </div>
            }
        </div>
        <p class="text-center">
            
        </p>
    </div>
</div>