ProjetoLP/AngelinaPrj/Controllers/ExercicioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AngelinaPrj.Models;
using AngelinaPrj.ViewModel;

namespace AngelinaPrj.Controllers
{
    public class ExercicioController : Controller
    {
        private PrjContext db = new PrjContext();


        // GET: Exercicios/DetalhesExercicio/
        public ActionResult DetalhesExercicio(int ? ExercicioId)
        {
            if (ExercicioId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Exercicio exercicio = db.Exercicios.Find(ExercicioId);

            if (exercicio == null)
            {
                return HttpNotFound();
            }
            return View(exercicio);
        }

        // GET: Exercicios/CriarExercicio/
        public ActionResult CriarExercicio(int ? MaterialId)
        {
            if (MaterialId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            else
            {
                int materialId = Convert.ToInt16(MaterialId);

                CadastroExercicioViewModel exercicio = new CadastroExercicioViewModel
                {
                    MaterialId = materialId
                };

                return View(exercicio);
            }
        }

        // POST: Exercicios/CriarExercicio/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CriarExercicio(HttpPostedFileBase file, CadastroExercicioViewModel viewmodel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewmodel);
            }

            if (file.ContentLength > 0)
            {
                var nomeArquivo = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Uploads"), nomeArquivo);

                file.SaveAs(path);

                Exercicio exercicio = new Exercicio()
                {
                    Proposta = viewmodel.Proposta,
                    Arquivo = path,
                    DataDeEntrega = viewmodel.DataDeEntrega,
                    MaterialId = viewmodel.MaterialId
                };

                db.Exercicios.Add(exercicio);
            }

            else
            {
                Exercicio exercicio = new Exercicio()
                {
                    Proposta = viewmodel.Proposta,
                    DataDeEntrega = viewmodel.DataDeEntrega,
                    MaterialId = viewmodel.MaterialId
                };

                db.Exercicios.Add(exercicio);
            }
            
            db.SaveChanges();

            var queryUltimoExercicio =
               (from e in db.Exercicios
                orderby e.ExercicioId descending
                select new { e.ExercicioId }).First();


            return RedirectToAction("DetalhesMaterial", "Material", new { MaterialId = queryUltimoExercicio.ExercicioId });


        }

        // GET: Exercicios/Edit/5
        public ActionResult EditarExercicio(int? ExercicioId)
        {
            if (ExercicioId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exercicio exercicio = db.Exercicios.Find(ExercicioId);
            if (exercicio == null)
            {
                return HttpNotFound();
            }
            return View(exercicio);
        }

        // POST: Exercicios/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarExercicio([Bind(Include = "ExercicioId,Proposta,Arquivo,DataDeEntrega")] Exercicio exercicio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(exercicio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(exercicio);
        }

        // GET: Exercicios/Delete/
        public ActionResult Delete(int? ExercicioId)
        {
            if (ExercicioId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exercicio exercicio = db.Exercicios.Find(ExercicioId);
            if (exercicio == null)
            {
                return HttpNotFound();
            }
            return View(exercicio);
        }

        // POST: Exercicios/Delete/
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int ExercicioId)
        {
            Exercicio exercicio = db.Exercicios.Find(ExercicioId);
            db.Exercicios.Remove(exercicio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetoLP/AngelinaPrj/Controllers/MateriaisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AngelinaPrj.Models;
using AngelinaPrj.ViewModel;

namespace AngelinaPrj.Controllers
{
    public class MateriaisController : Controller
    {
        private PrjContext db = new PrjContext();

        // GET: Materiais/DetalhesMaterial/
        [Authorize]
        public ActionResult DetalhesMaterial(int ? MaterialId)
        {
            if (MaterialId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Material material = db.Materiais.Find(MaterialId);

            if (material == null)
            {
                return HttpNotFound();
            }

            var exercicios = db.Exercicios.Where(m => m.MaterialId == MaterialId).ToList();

            var view = new DetalhesMaterialViewModel()
            {
                Material = material,
                Exercicios = exercicios
            };

            return View(view);
        }

        // GET: Materiais/CadastrarMaterial/
        [Authorize(Roles = "Professor")]
        public ActionResult CadastrarMaterial(int ? SalaId)
        {
            if (SalaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            else {
                int salaId = Convert.ToInt16(SalaId);

                CadastroMaterialViewModel material = new CadastroMaterialViewModel
                {
                    SalaId = salaId
                };

                return View(material);
            }
        }

        // POST: Materiais/CadastrarMaterial/
        [Authorize(Roles = "Professor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CadastrarMaterial(HttpPostedFileBase file, CadastroMaterialViewModel viewmodel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewmodel);
            }

            if (db.Materiais.Count(m => m.Assunto == viewmodel.Assunto) > 0)
            {
                if (db.Materiais.Count(m => m.Sala.SalaId == viewmodel.SalaId) > 0)
                {
                    ModelState.AddModelError("Assunto", "Este material já existe, altere o assunto para não gerar ambiguidade.");
                    return View(viewmodel);
                }
            }

            if (file.ContentLength > 0)
            {
                var nomeArquivo = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Uploads"), nomeArquivo);

                file.SaveAs(path);

                Material material = new Material
                {
                    Resumo = viewmodel.Resumo,
                    Assunto = viewmodel.Assunto,
                    Data = DateTime.Now,
                    Descricao = viewmodel.Descricao,
                    SalaId = viewmodel.SalaId,
                    Arquivo = path
                };

                db.Materiais.Add(material);
            }
            else
            {
                Material material = new Material
                {
                    Resumo = viewmodel.Resumo,
                    Assunto = viewmodel.Assunto,
                    Data = DateTime.Now,
                    Descricao = viewmodel.Descricao,
                    SalaId = viewmodel.SalaId
                };

                db.Materiais.Add(material);
            }

            db.SaveChanges();

            var queryUltimoMaterial =
                (from m in db.Materiais
                 orderby m.MaterialId descending
                 select new { m.MaterialId }).First();


            return RedirectToAction("DetalhesMaterial", new { MaterialId = queryUltimoMaterial.MaterialId});
        }

        //GET: Materiais/DownloadMaterial/
        [Authorize]
        public FileResult DownloadMaterial(string arquivo)
        {
            var path = arquivo;

            FileStream fileStream;

            fileStream = System.IO.File.OpenRead(path);

            string contentType = "application/pdf";

            return File(fileStream, contentType);
        }

        // GET: Materiais/EditarMaterial/
        public ActionResult EditarMaterial(int? MaterialId)
        {
            if (MaterialId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Material material = db.Materiais.Find(MaterialId);

            if (material == null)
            {
                return HttpNotFound();
            }

            return View(material);
        }

        [Authorize(Roles = "Professor")]
        // POST: Materiais/EditarMaterial/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarMaterial([Bind(Include = "MaterialId,Assunto,Data,Descricao,Arquivo")] Material material)
        {
            if (ModelState.IsValid)
            {
                db.Entry(material).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(material);
        }

        // GET: Materiais/Delete/
        [Authorize(Roles = "Professor")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Material material = db.Materiais.Find(id);
            if (material == null)
            {
                return HttpNotFound();
            }
            return View(material);
        }

        // POST: Materiais/Delete/
        [Authorize(Roles = "Professor")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Material material = db.Materiais.Find(id);
            db.Materiais.Remove(material);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetoLP/AngelinaPrj/Views/Materiais/CadastrarMaterial.cshtml
@model AngelinaPrj.ViewModel.CadastroMaterialViewModel

@{
    ViewBag.Title = "CadastrarMaterial";
}

<h2>CadastrarMaterial</h2>

@using (Html.BeginForm("CadastrarMaterial", "Materiais", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CadastroMaterialViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Resumo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Resumo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Resumo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Assunto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Assunto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Assunto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="form-group">
                <label for="@Model.Arquivo">Arquivo</label>
                <input type="file" class="form-control-file" name="file">
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SalaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SalaId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SalaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProjetoLP/AngelinaPrj/Views/Materiais/Delete.cshtml
@model AngelinaPrj.Models.Material

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Material</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Assunto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Assunto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descrição)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descrição)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Arquivo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Arquivo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjetoLP/AngelinaPrj/Views/Materiais/DetalhesMaterial.cshtml
@model AngelinaPrj.ViewModel.DetalhesMaterialViewModel

@{ 
    var nomeMateria = @Model.Material.Sala.Materia;
}

@{
    ViewBag.Title = "Detalhes do Material em "+nomeMateria;
}

<h2 class="text-center col-8 d-block mx-auto mt-2">Detalhes do Material de @Model.Material.Data.Day/@Model.Material.Data.Month/@Model.Material.Data.Year em @Model.Material.Sala.Materia</h2>

<div class="container text-center">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Material.Resumo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Material.Resumo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Material.Assunto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Material.Assunto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Material.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Material.Data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Material.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Material.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Material.Arquivo)
        </dt>

        <dd>
            @Html.ActionLink("Download", "DownloadMaterial", new { arquivo = @Model.Material.Arquivo })
        </dd>

    </dl>
</div>

<h2 class="text-center col-8 d-block mx-auto mt-2">Exercícios</h2>

<div class="row justify-content-center">
    @foreach (var exercicio in Model.Exercicios)
    {

        <div class="card text-white bg-dark m-3 text-center" style="max-width: 18rem;">
            <div class="card-header">@exercicio.DataDeEntrega</div>
            <div class="card-body">
                <p class="card-text">Data de Entrega: @exercicio.Proposta</p>
                <p class="card-text">Arquivo de apoio: @Html.ActionLink("Download", "DownloadMaterial", new { arquivo = @Model.Material.Arquivo })</p>
            </div>
        </div>
    }
</div>
@{
    if (User.IsInRole("Professor"))
    {
        <p>
            @Html.ActionLink("Criar Exercício", "CriarExercicio", "Exercicio", new { MaterialId = Model.Material.MaterialId}, new { @class = "btn btn-primary"})
            @Html.ActionLink("Edit", "EditarMaterial", new { MaterialId = Model.Material.MaterialId }, new { @class = "btn btn-primary"})
            @Html.ActionLink("Voltar para lista de materiais", "Index")
        </p>
    }
}

ProjetoLP/AngelinaPrj/Views/Materiais/EditarMaterial.cshtml
@model AngelinaPrj.Models.Material

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Material</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaterialId)

        <div class="form-group">
            @Html.LabelFor(model => model.Assunto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Assunto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Assunto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Arquivo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Arquivo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Arquivo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "DetalhesMaterial", new { MaterialId = Model.MaterialId})
</div>

ProjetoLP/AngelinaPrj/Views/Materiais/Index.cshtml
@model IEnumerable<AngelinaPrj.Models.Material>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Assunto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descrição)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Arquivo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Assunto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descrição)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Arquivo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MaterialId }) |
            @Html.ActionLink("Details", "Details", new { id=item.MaterialId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MaterialId })
        </td>
    </tr>
}

</table>