ProjetoLP/AngelinaPrj/Models/Materia.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AngelinaPrj.Models
{
    [Table("Materias")]
    public class Materia
    {
        [Key]
        public int MateriaId { get; set; }

        [Required]
        [MaxLength(30)]
        public string Nome { get; set; }
        
        [MaxLength(500)]
        public string Descricao { get; set; }
        
        [MaxLength(100)]
        public string Professor { get; set; }

        [Required]
        public int CursoId { get; set; }

        public virtual ICollection<Curso_Materia> Curso_Materias { get; set; }

        public virtual ICollection<Materia_Sala> Materia_Salas { get; set; }
    }
}

ProjetoLP/AngelinaPrj/Controllers/CursoController.cs
using AngelinaPrj.Models;
using AngelinaPrj.ViewModel;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace AngelinaPrj.Controllers
{
    [Authorize(Roles = "Professor")]
    public class CursoController : Controller
    {
        private PrjContext db = new PrjContext();

        // GET: Curso/
        public ActionResult Index(int ? EscolaId)
        {
            if (EscolaId == null)
            {
                return View(db.Cursos.ToList());
            }

            return View(db.Cursos.Where(e => e.EscolaId == EscolaId).ToList());

        }

        // GET: Curso/CadastrarCurso
        public ActionResult CadastrarCurso(int EscolaId)
        {
            CadastroCursoViewModel curso = new CadastroCursoViewModel
            {
                Escola = EscolaId
            };

            return View(curso);
        }

        //POST: Curso/CadastrarCurso
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CadastrarCurso(CadastroCursoViewModel viewmodel, int EscolaId)
        {
            if (!ModelState.IsValid)
            {
                return View(viewmodel);
            }

            if (db.Cursos.Count(u => u.Nome == viewmodel.Nome) > 0)
            {
                if (db.Cursos.Count(u => u.EscolaId == EscolaId) > 0)
                {
                    ModelState.AddModelError("Nome", "Este curso já existe nesta escola !");
                    return View(viewmodel);
                }
            }

            Curso curso = new Curso
            {
                Nome = viewmodel.Nome,
                Descricao = viewmodel.Descricao,
                EscolaId = EscolaId
            };

            db.Cursos.Add(curso);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        //GET: Curso/EditarCurso
        public ActionResult EditarCurso(int ? CursoId, int EscolaId)
        {
            if (CursoId == null)
            {
                 return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Curso curso = db.Cursos.Find(CursoId);

            if (curso == null)
            {
                return HttpNotFound();
            }

            return View(curso);
        }

        //POST: Curso/EditarCurso
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarCurso([Bind(Include = "CursoId, Nome, Descricao, EscolaId, Escola, Materias")]Curso curso)
        {
            if (!ModelState.IsValid)
            {
                return View(curso);
            }

            db.Entry(curso).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        //GET: Curso/DeletarCurso
        public ActionResult Delete(int ? CursoId)
        {
            if (CursoId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Curso curso = db.Cursos.Find(CursoId);

            if (curso == null)
            {
                return HttpNotFound();
            }

            return View(curso);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        //POST: Curso/DeletarCurso
        public ActionResult DeleteConfirmed(int CursoId)
        {
            Curso curso = db.Cursos.Find(CursoId);
            db.Cursos.Remove(curso);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //GET: Curso/DetalhesCurso
        public ActionResult DetalhesCurso(int ? CursoId, int ? EscolaId)
        {
            if (EscolaId == null || CursoId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Curso curso = db.Cursos.Find(CursoId);

            if (curso == null)
            {
                return HttpNotFound();
            }

            var materias = db.Materias.Where(m => m.CursoId == CursoId).ToList();

            var view = new DetalhesCursoViewModel
            {
                Curso = curso,
                Materias = materias
            };

            return View(view);
        }

       
    }
}

ProjetoLP/AngelinaPrj/Controllers/PainelController.cs
using AngelinaPrj.Models;
using AngelinaPrj.ViewModel;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace AngelinaPrj.Controllers
{
    [Authorize(Roles = "Professor")]
    public class PainelController : Controller
    {
        private PrjContext db = new PrjContext();

        // GET: Painel
        public ActionResult Index()
        {
            return View(db.Escolas.ToList());
        }

        //GET: Painel/CadastrarEscola
        public ActionResult CadastrarEscola()
        {
            return View();
        }

        //POST: Painel/CadastrarEscola
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CadastrarEscola(CadastroEscolaViewModel viewmodel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewmodel);
            }

            if (db.Escolas.Count(u => u.Nome == viewmodel.Nome) > 0)
            {
                ModelState.AddModelError("Nome", "Esta escola já está cadastrada");
                return View(viewmodel);

            }

            Escola novaEscola = new Escola
            {
                Nome = viewmodel.Nome,
                Cidade = viewmodel.Cidade
            };

            db.Escolas.Add(novaEscola);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        //GET: Painel/EditarEscola
        public ActionResult EditarEscola(int? EscolaId)
        {
            if (EscolaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Escola escola = db.Escolas.Find(EscolaId);

            if (escola == null)
            {
                return HttpNotFound();
            }

            return View(escola);
        }

        //POST: Painel/EditarEscola
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarEscola([Bind(Include = "EscolaId,Nome,Cidade")]Escola escola)
        {
            if (!ModelState.IsValid)
            {
                return View(escola);
            }

            db.Entry(escola).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: Painel/DeletarEscola
        public ActionResult Delete(int? EscolaId)
        {
            if (EscolaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Escola escola = db.Escolas.Find(EscolaId);
            if (escola == null)
            {
                return HttpNotFound();
            }
            return View(escola);
        }

        // POST: Painel/DeletarEscola
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int EscolaId)
        {
            Escola escola = db.Escolas.Find(EscolaId);
            db.Escolas.Remove(escola);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Painel/DetalhesEscola
        public ActionResult DetalhesEscola(int? EscolaId)
        {
            if (EscolaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Escola escola = db.Escolas.Find(EscolaId);

            if (escola == null)
            {
                return HttpNotFound();
            }

            var cursos = db.Cursos.Where(e => e.EscolaId == EscolaId).ToList();

            var view = new DetalhesEscolaViewModel()
            {
                Escola = escola,
                Cursos = cursos
            };

            return View(view);
        }
    }   
}

ProjetoLP/AngelinaPrj/Controllers/SalaController.cs
using AngelinaPrj.Models;
using AngelinaPrj.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace AngelinaPrj.Controllers
{
    [Authorize]
    public class SalaController : Controller
    {
        private PrjContext db = new PrjContext();

        // GET: Sala/
        [Authorize(Roles = "Professor")]
        public ActionResult Index(int ? MateriaId)
        {
            if (MateriaId == null)
            {
                return View(db.Salas.ToList());
            }
            var listaSalas = new List<Materia_Sala>();
            listaSalas = db.Materias_Salas.Where(s => s.MateriaId == MateriaId).ToList();

            var listaMaterias = new List<Materia>();
            listaMaterias = db.Materias.ToList();

            ViewBag.Materias = listaMaterias;

            return View(listaSalas);
        }

        //GET: Sala/CadastrarSala
        [Authorize(Roles = "Professor")]
        public ActionResult CadastrarSala(int MateriaId)
        {
            CadastroSalaViewModel sala = new CadastroSalaViewModel
            {
                MateriaId = MateriaId
            };

            return View(sala);
        }

        //POST: Sala/CadastrarSala
        [Authorize(Roles = "Professor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CadastrarSala(CadastroSalaViewModel viewmodel, int MateriaId)
        {
            if (!ModelState.IsValid)
            {
                return View(viewmodel);
            }
                Random rand = new Random((int)DateTime.Now.Ticks);
                var CodigoSala = 0;
                CodigoSala = rand.Next(1000, 9999);

            //criar aqui as querys que procuram o nome da escola e da matéria
            //pela matéria eu consigo o curso e pelo curso eu consigo a escola

            var queryNomeMateria =
                (from nMateria in db.Materias
                 where nMateria.MateriaId == MateriaId
                 select new { nMateria.Nome }).Single();

            var queryCursoId =
                (from cId in db.Materias
                 where cId.MateriaId == MateriaId
                 select new { cId.CursoId }).Single();

            var queryEscolaId =
                (from eId in db.Cursos
                 where eId.CursoId == queryCursoId.CursoId
                 select new { eId.EscolaId }).Single();

            var queryNomeEscola =
                (from nEscola in db.Escolas
                 where nEscola.EscolaId == queryEscolaId.EscolaId
                 select new { nEscola.Nome }).Single();

            Sala sala = new Sala
            {
                Semestre = viewmodel.Semestre,
                Situacao = viewmodel.Situacao,
                Periodo = viewmodel.Periodo,
                CodigoSala = CodigoSala,
                Escola = queryNomeEscola.Nome,
                Materia = queryNomeMateria.Nome
            };

            db.Salas.Add(sala);
            db.SaveChanges();

            Materia_Sala sala_materia = new Materia_Sala
            {
                MateriaId = MateriaId,
                SalaId = sala.SalaId
            };

            db.Materias_Salas.Add(sala_materia);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        //GET Sala/SalasAluno
        [Authorize(Roles = "Aluno")]
        public ActionResult SalasAlunoById(int UsuarioId)
        {
            var queryVerificaAluno = db.Usuarios.Where(u => u.Nome == User.Identity.Name).FirstOrDefault();

            int IdUsuarioSolicitado = queryVerificaAluno.UsuarioId;

            if (UsuarioId == IdUsuarioSolicitado)
            {
                var querySalasDoAluno = db.Alunos_Sala.AsQueryable().AsEnumerable();

                querySalasDoAluno = querySalasDoAluno.Where(s => s.UsuarioId == UsuarioId);

                return View(querySalasDoAluno);
            }

            else
            {
                return RedirectToAction("Index", "Home", null);
            }
        }

        //GET Sala/SalasAluno
        [Authorize]
        public ActionResult SalasAlunoByName(string NomeUsuario)
        {
            var queryProcuraIdUsuario = db.Usuarios.AsQueryable().Where(u => u.Nome == NomeUsuario).FirstOrDefault();

            int UsuarioId = queryProcuraIdUsuario.UsuarioId;

            return (RedirectToAction("SalasAlunoById", new { UsuarioId = UsuarioId}));
        }

        //GET: Sala/EditarSala
        [Authorize(Roles = "Professor")]
        public ActionResult EditarSala(int ? SalaId)
        {
            if (SalaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Sala sala = db.Salas.Find(SalaId);

            if (sala == null)
            {
                return HttpNotFound();
            }

            return View(sala);
        }


        //POST: Sala/EditarSala
        [Authorize(Roles = "Professor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarSala([Bind(Include = "SalaId, Semestre, Situacao, Periodo, CodigoSala, Escola, Materia")] Sala sala)
        {
            if (!ModelState.IsValid)
            {
                return View(sala);
            }

            db.Entry(sala).State = EntityState.Modified;
            db.SaveChanges();

            return View(sala);
        }

        //GET Sala/DetalhesSala
        [Authorize(Roles = "Aluno, Professor")]
        public ActionResult DetalhesSala(int? SalaId)
        {
            if (SalaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Sala sala = db.Salas.Find(SalaId);

            if (sala == null)
            {
                return HttpNotFound();
            }

            var materiais = db.Materiais.Where(m => m.Sala.SalaId == sala.SalaId).ToList();

            if (materiais == null)
            {
                return HttpNotFound();
            }

            var viewmodel = new DetalhesSalaViewModel
            {
                Sala = sala,

                Materiais = materiais
            };

            return View(viewmodel);
        }
    }
        
}

ProjetoLP/AngelinaPrj/Views/Materia/CadastrarMateria.cshtml
@model AngelinaPrj.ViewModel.CadastroMateriaViewModel

@{
    ViewBag.Title = "CadastrarMateria";
}

<div class="container min-vh-100">
    <h2>Cadastrar materia</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>CadastroMateriaViewModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Professor, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Professor, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Professor, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Criar" class="btn btn-default" />
                    @Html.ActionLink("Voltar para lista de matérias", "DetalhesCurso", "Curso")
                </div>
            </div>
        </div>
    }

    <div>
        
    </div>
</div>

ProjetoLP/AngelinaPrj/Views/Materia/DetalhesMateria.cshtml
@model AngelinaPrj.ViewModel.DetalhesMateriaViewModel
@{
                /**/

                ViewBag.Title = "DetalhesMateria";
}
<div class="container">
    <h2 class="text-center m-2">Salas de @Model.Materia.Nome</h2>
    <div class="col-12">
        <div class="row justify-content-center">
            @foreach (var sala in Model.Materia_Salas)
            {
                <div class="card text-white bg-dark m-3 text-center" style="max-width: 18rem;">
                    <div class="card-header">Escola: @sala.Salas.Escola</div>
                    <div class="card-body">
                        <p class="card-text">Semestre: @sala.Salas.Semestre</p>
                        <p class="card-text">Período: @sala.Salas.Periodo</p>
                        <p class="card-text">Materia: @sala.Materia.Nome</p>
                        @{
                            if (sala.Salas.Situacao == true)
                            {
                                <p class="card-text"><span class="badge badge-success">Em andamento</span></p>
                            }
                            else
                            {
                                <span class="badge badge-danger">Sala fechada !</span>
                            }
                        }
                    </div>
                    @Html.ActionLink("Ver materiais da sala", "DetalhesSala", "Sala", new { SalaId = sala.SalaId}, new { @class = "btn btn-primary mx-1 my-1" })
                    @Html.ActionLink("Alterar situação", "EditarSala", "Sala", new { SalaId = sala.SalaId }, new { @class = "btn btn-danger mx-1 my-1" })
                </div>
            }
        </div>
        @Html.ActionLink("Nova Sala", "CadastrarSala", "Sala", new { MateriaId = Model.Materia.MateriaId}, null)
    </div>
</div>
@Html.ActionLink("Nova Sala", "CadastrarSala", "Sala", new { MateriaId = Model.Materia.MateriaId }, null)

ProjetoLP/AngelinaPrj/Views/Materia/EditarMateria.cshtml
@model AngelinaPrj.Models.Materia

@{
    ViewBag.Title = "EditarMateria";
}
<div class="container">
    <h2>EditarMateria</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Materia</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.MateriaId)

            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Professor, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Professor, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Professor, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

ProjetoLP/AngelinaPrj/Views/Materia/Index.cshtml
@model IEnumerable<AngelinaPrj.Models.Materia>

@{
    ViewBag.Title = "Index";
}


<h2></h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Professor)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MateriaId }) |
            @Html.ActionLink("Details", "Details", new { id=item.MateriaId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MateriaId })
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Lista de escolas", "Index", "Painel", null, new { @class = "btn btn-primary" })
</div>