ProjetoLP/AngelinaPrj/Controllers/PainelController.cs
using AngelinaPrj.Models;
using AngelinaPrj.ViewModel;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace AngelinaPrj.Controllers
{
    [Authorize(Roles = "Professor")]
    public class PainelController : Controller
    {
        private PrjContext db = new PrjContext();

        // GET: Painel
        public ActionResult Index()
        {
            return View(db.Escolas.ToList());
        }

        //GET: Painel/CadastrarEscola
        public ActionResult CadastrarEscola()
        {
            return View();
        }

        //POST: Painel/CadastrarEscola
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CadastrarEscola(CadastroEscolaViewModel viewmodel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewmodel);
            }

            if (db.Escolas.Count(u => u.Nome == viewmodel.Nome) > 0)
            {
                ModelState.AddModelError("Nome", "Esta escola já está cadastrada");
                return View(viewmodel);

            }

            Escola novaEscola = new Escola
            {
                Nome = viewmodel.Nome,
                Cidade = viewmodel.Cidade
            };

            db.Escolas.Add(novaEscola);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        //GET: Painel/EditarEscola
        public ActionResult EditarEscola(int? EscolaId)
        {
            if (EscolaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Escola escola = db.Escolas.Find(EscolaId);

            if (escola == null)
            {
                return HttpNotFound();
            }

            return View(escola);
        }

        //POST: Painel/EditarEscola
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarEscola([Bind(Include = "EscolaId,Nome,Cidade")]Escola escola)
        {
            if (!ModelState.IsValid)
            {
                return View(escola);
            }

            db.Entry(escola).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: Painel/DeletarEscola
        public ActionResult Delete(int? EscolaId)
        {
            if (EscolaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Escola escola = db.Escolas.Find(EscolaId);
            if (escola == null)
            {
                return HttpNotFound();
            }
            return View(escola);
        }

        // POST: Painel/DeletarEscola
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int EscolaId)
        {
            Escola escola = db.Escolas.Find(EscolaId);
            db.Escolas.Remove(escola);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Painel/DetalhesEscola
        public ActionResult DetalhesEscola(int? EscolaId)
        {
            if (EscolaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Escola escola = db.Escolas.Find(EscolaId);

            if (escola == null)
            {
                return HttpNotFound();
            }

            var cursos = db.Cursos.Where(e => e.EscolaId == EscolaId).ToList();

            var view = new DetalhesEscolaViewModel()
            {
                Escola = escola,
                Cursos = cursos
            };

            return View(view);
        }
    }   
}

ProjetoLP/AngelinaPrj/Controllers/PerfilController.cs
using AngelinaPrj.Models;
using AngelinaPrj.Utils;
using AngelinaPrj.ViewModel;
using System.Linq;
using System.Security.Claims;
using System.Web.Mvc;

namespace AngelinaPrj.Controllers
{

    [Authorize]
    public class PerfilController : Controller
    {
        private PrjContext db = new PrjContext();

        // GET: Perfil/AlterarSenha
        public ActionResult AlterarSenha()
        {
            return View();
        }

        //POST: Perfil/AlterarSenha
        [HttpPost]
        public ActionResult AlterarSenha(AlteraSenhaViewModel viewmodel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var identity = User.Identity as ClaimsIdentity;
            var login = identity.Claims.FirstOrDefault(c => c.Type == "Email").Value;

            var usuario = db.Usuarios.FirstOrDefault(u => u.Email == login);

            if (Hash.GerarHash(viewmodel.SenhaAtual) != usuario.Senha)
            {
                ModelState.AddModelError("SenhaAtual", "Senha incorreta");
                return View();
            }

            usuario.Senha = Hash.GerarHash(viewmodel.NovaSenha);
            db.Entry(usuario).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();

            TempData["Mensagem"] = "Senha alterada com sucesso";

            return RedirectToAction("Index", "Painel");
        }

        //GET: Perfil/Mensagens
        public ActionResult Mensagens()
        {
            return View();
        }

    }
}

ProjetoLP/AngelinaPrj/Controllers/SalaController.cs
using AngelinaPrj.Models;
using AngelinaPrj.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace AngelinaPrj.Controllers
{
    [Authorize]
    public class SalaController : Controller
    {
        private PrjContext db = new PrjContext();

        // GET: Sala/
        [Authorize(Roles = "Professor")]
        public ActionResult Index(int ? MateriaId)
        {
            if (MateriaId == null)
            {
                return View(db.Salas.ToList());
            }
            var listaSalas = new List<Materia_Sala>();
            listaSalas = db.Materias_Salas.Where(s => s.MateriaId == MateriaId).ToList();

            var listaMaterias = new List<Materia>();
            listaMaterias = db.Materias.ToList();

            ViewBag.Materias = listaMaterias;

            return View(listaSalas);
        }

        //GET: Sala/CadastrarSala
        [Authorize(Roles = "Professor")]
        public ActionResult CadastrarSala(int MateriaId)
        {
            CadastroSalaViewModel sala = new CadastroSalaViewModel
            {
                MateriaId = MateriaId
            };

            return View(sala);
        }

        //POST: Sala/CadastrarSala
        [Authorize(Roles = "Professor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CadastrarSala(CadastroSalaViewModel viewmodel, int MateriaId)
        {
            if (!ModelState.IsValid)
            {
                return View(viewmodel);
            }
                Random rand = new Random((int)DateTime.Now.Ticks);
                var CodigoSala = 0;
                CodigoSala = rand.Next(1000, 9999);

            //criar aqui as querys que procuram o nome da escola e da matéria
            //pela matéria eu consigo o curso e pelo curso eu consigo a escola

            var queryNomeMateria =
                (from nMateria in db.Materias
                 where nMateria.MateriaId == MateriaId
                 select new { nMateria.Nome }).Single();

            var queryCursoId =
                (from cId in db.Materias
                 where cId.MateriaId == MateriaId
                 select new { cId.CursoId }).Single();

            var queryEscolaId =
                (from eId in db.Cursos
                 where eId.CursoId == queryCursoId.CursoId
                 select new { eId.EscolaId }).Single();

            var queryNomeEscola =
                (from nEscola in db.Escolas
                 where nEscola.EscolaId == queryEscolaId.EscolaId
                 select new { nEscola.Nome }).Single();

            Sala sala = new Sala
            {
                Semestre = viewmodel.Semestre,
                Situacao = viewmodel.Situacao,
                Periodo = viewmodel.Periodo,
                CodigoSala = CodigoSala,
                Escola = queryNomeEscola.Nome,
                Materia = queryNomeMateria.Nome
            };

            db.Salas.Add(sala);
            db.SaveChanges();

            Materia_Sala sala_materia = new Materia_Sala
            {
                MateriaId = MateriaId,
                SalaId = sala.SalaId
            };

            db.Materias_Salas.Add(sala_materia);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        //GET Sala/SalasAluno
        [Authorize(Roles = "Aluno")]
        public ActionResult SalasAlunoById(int UsuarioId)
        {
            var queryVerificaAluno = db.Usuarios.Where(u => u.Nome == User.Identity.Name).FirstOrDefault();

            int IdUsuarioSolicitado = queryVerificaAluno.UsuarioId;

            if (UsuarioId == IdUsuarioSolicitado)
            {
                var querySalasDoAluno = db.Alunos_Sala.AsQueryable().AsEnumerable();

                querySalasDoAluno = querySalasDoAluno.Where(s => s.UsuarioId == UsuarioId);

                return View(querySalasDoAluno);
            }

            else
            {
                return RedirectToAction("Index", "Home", null);
            }
        }

        //GET Sala/SalasAluno
        [Authorize]
        public ActionResult SalasAlunoByName(string NomeUsuario)
        {
            var queryProcuraIdUsuario = db.Usuarios.AsQueryable().Where(u => u.Nome == NomeUsuario).FirstOrDefault();

            int UsuarioId = queryProcuraIdUsuario.UsuarioId;

            return (RedirectToAction("SalasAlunoById", new { UsuarioId = UsuarioId}));
        }

        //GET: Sala/EditarSala
        [Authorize(Roles = "Professor")]
        public ActionResult EditarSala(int ? SalaId)
        {
            if (SalaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Sala sala = db.Salas.Find(SalaId);

            if (sala == null)
            {
                return HttpNotFound();
            }

            return View(sala);
        }


        //POST: Sala/EditarSala
        [Authorize(Roles = "Professor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarSala([Bind(Include = "SalaId, Semestre, Situacao, Periodo, CodigoSala, Escola, Materia")] Sala sala)
        {
            if (!ModelState.IsValid)
            {
                return View(sala);
            }

            db.Entry(sala).State = EntityState.Modified;
            db.SaveChanges();

            return View(sala);
        }

        //GET Sala/DetalhesSala
        [Authorize(Roles = "Aluno, Professor")]
        public ActionResult DetalhesSala(int? SalaId)
        {
            if (SalaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Sala sala = db.Salas.Find(SalaId);

            if (sala == null)
            {
                return HttpNotFound();
            }

            var materiais = db.Materiais.Where(m => m.Sala.SalaId == sala.SalaId).ToList();

            if (materiais == null)
            {
                return HttpNotFound();
            }

            var viewmodel = new DetalhesSalaViewModel
            {
                Sala = sala,

                Materiais = materiais
            };

            return View(viewmodel);
        }
    }
        
}

ProjetoLP/AngelinaPrj/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/magnific-popup.css" rel="stylesheet" />

    <!-- Fontes-->
    <link href="~/Content/fontawesome/css/all.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
</head>
<body id="page-top">
    <!-- Menu Superior -->
    <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase navbar-shrink" id="mainNav">
        <div class="container">
            @Html.ActionLink("Nome Professor", "Index", "Home", new { area = "" }, new { @class = "navbar-brand js-scroll-trigger" })
            <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item mx-0 mx-lg-1">
                            @Html.ActionLink("Cadastre-se", "Cadastrar", "Autenticacao", null, new { @class = "nav-link nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger"})
                        </li>
                        <li class="nav-item mx-0 mx-lg-1">
                            @Html.ActionLink("Login", "Login", "Autenticacao", null, new { @class = "nav-link nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" })
                        </li>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item mx-0 mx-lg-1 dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@User.Identity.Name</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @if (User.IsInRole("Professor"))
                                {
                                    @Html.ActionLink("Escolas", "Index", "Painel", null, new { @class = "mx-0 mx-lg-1 dropdown-item" })
                                    @Html.ActionLink("Salas", "Index", "Sala", null, new { @class = "mx-0 mx-lg-1 dropdown-item" })
                                    @Html.ActionLink("Alterar senha", "AlterarSenha", "Perfil", null, new { @class = "mx-0 mx-lg-1 dropdown-item" })
                                    @Html.ActionLink("Configurações", "ConfigsSite", "Painel", new { ProfessorId = 1 }, new { @class = "mx-0 mx-lg-1 dropdown-item" })
                                    <div class="dropdown-divider"></div>
                                    @Html.ActionLink("Sair", "Logout", "Autenticacao", null, new { @class = "mx-0 mx-lg-1 dropdown-item" })
                                }
                                else
                                {   
                                    @Html.ActionLink("Salas", "SalasAlunoByName", "Sala", new { NomeUsuario = User.Identity.Name }, new { @class = "mx-0 mx-lg-1 dropdown-item" })
                                    @Html.ActionLink("Alterar senha", "AlterarSenha", "Perfil", null, new { @class = "mx-0 mx-lg-1 dropdown-item" })
                                    <div class="dropdown-divider"></div>
                                    @Html.ActionLink("Sair", "Logout", "Autenticacao", null, new { @class = "mx-0 mx-lg-1 dropdown-item" })
                                }
                            </div>
                        </li>
                    }

                </ul>
            </div>
        </div>
    </nav>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
        @Html.ActionLink("Nome Professor", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav ml-auto">
                @if (!User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        @Html.ActionLink("Cadastre-se", "Cadastrar", "Autenticacao", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Login", "Login", "Autenticacao", null, new { @class = "nav-link" })
                    </li>
                }

                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@User.Identity.Name</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @if (User.IsInRole("Professor"))
                            {
                                @Html.ActionLink("Escolas", "Index", "Painel", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Salas", "Index", "Sala", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Alterar senha", "AlterarSenha", "Perfil", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Configurações", "ConfigsSite", "Painel", new { ProfessorId = 1 }, new { @class = "dropdown-item" })
                                <div class="dropdown-divider"></div>
                                @Html.ActionLink("Sair", "Logout", "Autenticacao", null, new { @class = "dropdown-item" })
                            }
                        </div>
                    </li>
                }
            </ul>
        </div>
    </nav>
        @RenderBody()
    <!-- Botão Topo (Apenas Extra pequeno e pequeno) -->
    <div class="scroll-to-top d-lg-none position-fixed">
        <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>
    <footer class="footer text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-4 mx-auto mb-lg-0">
                    <h4 class="text-uppercase mb-4">Redes Sociais</h4>
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item">
                            <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
                                <i class="fab fa-fw fa-facebook-f"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
                                <i class="fab fa-fw fa-google-plus-g"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
                                <i class="fab fa-fw fa-twitter"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
                                <i class="fab fa-fw fa-linkedin-in"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
                                <i class="fab fa-fw fa-dribbble"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <div class="copyright py-4 text-center text-white">
        <div class="container">
            <small>Copyright &copy; @DateTime.Now.Year</small>
        </div>
    </div>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/umd/popper.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>

    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <script src="~/Scripts/jquery.easing.js"></script>
    <script src="~/Scripts/jquery.magnific-popup.js"></script>
    <script src="~/Scripts/Site.js"></script>

</body>
</html>